name: CI/CD Workflow

on:
  push:
    branches: [master]

jobs:
  maven_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Build 'QuizAnalytics'
        run: mvn clean install -f QuizAnalytics

      - name: Build 'QuizSubmission'
        run: mvn clean install -f QuizSubmission

      - name: Build 'AnalyticsService'
        run: mvn clean install -f AnalyticsService

      - name: Build 'authentication-service'
        run: mvn clean install -f authentication-service

  docker_build:
    runs-on: ubuntu-latest
    needs: maven_build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Images
        run: docker-compose -f ${{ github.workspace }}/docker-compose.yml build

  docker_push:
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Images
        run: docker-compose -f ${{ github.workspace }}/docker-compose.yml push

  prune_images:
    runs-on: ubuntu-latest
    needs: docker_push
    steps:
      - name: Prune Docker Images
        if: always()
        run: docker image prune -f
