name: CI/CD Workflow

on:
  push:
    branches: [master]

jobs:
  maven_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Build 'QuizAnalytics'
        run: mvn clean install -f QuizAnalytics

      - name: Build 'QuizSubmission'
        run: mvn clean install -f QuizSubmission

      - name: Build 'AnalyticsService'
        run: mvn clean install -f AnalyticsService

      - name: Build 'authentication-service'
        run: mvn clean install -f authentication-service

  docker_build_and_publish:
    runs-on: ubuntu-latest
    needs: maven_build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Images
        run: docker-compose -f docker-compose.yml build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Images
        run: |
          export QUIZ_SUBMISSION_APP_IMAGE=jafarfarwaneh/quiz-submission-app
          export AUTHENTICATION_SERVICE_IMAGE=jafarfarwaneh/authentication-service
          export ANALYTICS_SERVICE_IMAGE=jafarfarwaneh/analytics-service
          export QUIZ_ANALYTICS_APP_IMAGE=jafarfarwaneh/quiz-analytics-app 
          docker-compose -f docker-compose.yml push
        
      - name: Prune Docker Images
        if: always()
        run: docker image prune -f
